apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: "hello-world"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.service.port | default 8080 }}
    targetPort: {{ .Values.service.targetPort | default 8080 }}
    protocol: TCP
  - name: metrics
    port: {{ .Values.service.metricsPort | default 9090 }}
    targetPort: {{ .Values.service.metricsTargetPort | default 9090 }}
    protocol: TCP
  selector:
    app: "hello-world"
