name: Docker Build and Push

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *' # This will run every day at midnight UTC

jobs:
  Test:
    runs-on: self-hosted-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HUGO test build
        run: |
          docker run --rm -v $(pwd)/blog/:/src -w /src thegeeklab/hugo:latest --panicOnWarning --minify --gc --cleanDestinationDir --destination public --baseURL http://localhost
        
      # - name: html-validation
      #   run: |
      #     docker run --rm -v $(pwd)/blog/:/src -w /src thegeeklab/vnu vnu --skip-non-html --errors-only --filterfile .vnuignore public/
      
      - name: Checking for expired content
        run: |
          docker run --rm -v $(pwd)/blog/:/src -w /src thegeeklab/hugo:0.122 list expired

  Build:
    runs-on: self-hosted-runner
    needs: Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker build and push
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --pull \
            --build-arg VERSION="v${{ github.run_number }}" \
            --build-arg GIT_COMMIT="${{ github.sha }}" \
            --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')" \
            --cache-from supporttools/hello-world:latest \
            -t supporttools/hello-world:v${{ github.run_number }} \
            -t supporttools/hello-world:latest \
            --push \
            -f Dockerfile .

  Publish:
    runs-on: self-hosted-runner
    needs: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gettext
        run: |
          sudo apt-get update && sudo apt-get install -y gettext        
      
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Helm Lint
        run: helm lint charts/hello-world/

      - name: Package Helm chart
        run: |
          export CHART_VERSION="v${{ github.run_number }}"
          export APP_VERSION="v${{ github.run_number }}"
          export IMAGE_TAG="v${{ github.run_number }}"
          echo "CHART_VERSION=${CHART_VERSION}"
          echo "APP_VERSION=${APP_VERSION}"
          echo "IMAGE_TAG=${IMAGE_TAG}"
          envsubst < charts/hello-world/Chart.yaml.template > charts/hello-world/Chart.yaml
          envsubst < charts/hello-world/values.yaml.template > charts/hello-world/values.yaml
          helm package charts/hello-world --destination helm/repo

      - name: Checkout helm-chart repository
        uses: actions/checkout@v4
        with:
          repository: SupportTools/helm-chart
          path: helm-chart
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

      - name: Update Helm repository
        run: |
          cp helm/repo/hello-world-*.tgz helm-chart/
          cd helm-chart
          helm repo index . --url https://charts.support.tools/
          git add .
          git commit -m "Update Helm chart for support.tools"
          git push
